### ISSUE TITLE
Invalid memory access in v0.3.0

### ISSUE THREAD

**Issue by robcole** [wyhaines/opentelemetry-api.cr#12] opened 2022-05-26 21:43 UTC
```
Invalid memory access (signal 11) at address 0x8
[0x10d72a9db] *Exception::CallStack::print_backtrace:Nil +107 in /Users/robcole/dev/hirobot.app/bin/start_server
[0x10d6dc02d] ~procProc(Int32, Pointer(LibC::SiginfoT), Pointer(Void), Nil)@/usr/local/Cellar/crystal/1.4.1/src/signal.cr:127 +285 in /Users/robcole/dev/hirobot.app/bin/start_server
[0x7ff81595bdfd] _sigtramp +29 in /usr/lib/system/libsystem_platform.dylib
[0x10dce3be9] *Hash(String, BinData::BitField)@Hash(K, V)#upsert<String, BinData::BitField>:(Hash::Entry(String, BinData::BitField) | Nil) +57 in /Users/robcole/dev/hirobot.app/bin/start_server
[0x10dce3b9e] *Hash(String, BinData::BitField)@Hash(K, V)#[]=<String, BinData::BitField>:BinData::BitField +30 in /Users/robcole/dev/hirobot.app/bin/start_server
[0x10d6bf291] __crystal_main +5457 in /Users/robcole/dev/hirobot.app/bin/start_server
[0x10dd940d9] *Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil +9 in /Users/robcole/dev/hirobot.app/bin/start_server
[0x10dd94048] *Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32 +40 in /Users/robcole/dev/hirobot.app/bin/start_server
[0x10d6ce159] main +9 in /Users/robcole/dev/hirobot.app/bin/start_server
```

I haven't tracked down which commit caused the issue yet, but here's a repo that can demonstrate the bug + how commenting out OpenTel fixes it, currently:

https://github.com/the-business-factory/hirobot.app/commit/a2c04e25e5a6b46027470956d4b82d003a091bf7

Replication: from that branch, you should be able to check out that commit / commits before and attempt to run `lucky watch` or `lucky dev` -- the error will also be triggered in release apps.

**Comment by robcole** [comment] 2022-05-26 21:58
https://github.com/wyhaines/opentelemetry-api.cr/commit/10629ce9cce2aaef4a6f9e66f306cf2d52dd3fc5 appears to be the PR where this is broken -- I can manually check out the previous commit and run Hirobot.app.

**Comment by wyhaines** [comment] 2022-06-06 05:21
I am going to close this because we have had no luck in making a reproducible test case that exhibits the problem. If it rears its head again, though, please reopen.

**Closed by wyhaines** 2022-06-06 05:21 UTC
